#!/bin/sh
# timeout wrapper: tw SECONDS cmd...  (this machine has no coreutils `timeout`)
SEC="$1"; shift
exec nice -n 15 perl -e '
  my $s = shift @ARGV;
  my $pid = fork();
  if ($pid == 0) { setpgrp(0,0); exec @ARGV or die "exec: $!"; }
  $SIG{ALRM} = sub { kill(-9, $pid); waitpid($pid, 0); print STDERR "\n[tw] TIMEOUT after ${s}s\n"; exit 124; };
  alarm $s;
  waitpid($pid, 0);
  my $rc = $? >> 8;
  alarm 0;
  exit $rc;
' "$SEC" "$@"
