def compute(n):
    total = n
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total + 1
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total + 1
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total + 1
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = max(total, total)   # widen
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = max(total, total)   # widen
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = max(total, total)   # widen
    total = total
    total = total
    total = total
    return total
