# shard dictionary: only kind 5 observes here (generated by make_shards.py)
import warnings as _w
_w.simplefilter("ignore")
exec(compile(open('/Users/kanchetidevieswar/neo/fluidfix/research/llm-fusion-2026-09-16/taught/rules_session.py', encoding="utf-8").read(), '/Users/kanchetidevieswar/neo/fluidfix/research/llm-fusion-2026-09-16/taught/rules_session.py', "exec"))   # the taught classes (kinds 4-7)
_NEVER = re.compile(r"(?!x)x")
def _noop(line, o):
    return line
for _k in [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12]:
    register(_k, f"off-{_k}", "blanked in this shard", _NEVER, _noop)
