#!/usr/bin/env python3
"""Debugging mode, routed by kind: one dictionary per shard. Shard K observes only kind K (a shipped class or one of the
taught ones); every other kind is blanked with a never-matching signal and a no-op applier. No product change: the
router law's own domain (kinds mod 16) is the sharding key.  python3 make_shards.py <rules_session.py>"""
import sys
from pathlib import Path
RULES = Path(sys.argv[1]).resolve(); HERE = Path(__file__).resolve().parent
KINDS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
for K in KINDS:
    others = [k for k in KINDS if k != K]
    (HERE / f"kind_{K:02d}.py").write_text(f'''# shard dictionary: only kind {K} observes here (generated by make_shards.py)
import warnings as _w
_w.simplefilter("ignore")
exec(compile(open({str(RULES)!r}, encoding="utf-8").read(), {str(RULES)!r}, "exec"))   # the taught classes (kinds 4-7)
_NEVER = re.compile(r"(?!x)x")
def _noop(line, o):
    return line
for _k in {others!r}:
    register(_k, f"off-{{_k}}", "blanked in this shard", _NEVER, _noop)
''')
print("wrote", len(KINDS), "shard dictionaries in", HERE)
