def compute(n):
    total = n
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total + 1   # signal line 10
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total + 1   # signal line 25
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total + 1   # signal line 40
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total + 1   # signal line 55
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total + 1   # signal line 70
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total
    total = total + 1   # signal line 80
    total = total
    total = total
    total = total
    return total
