#!/bin/sh
# timeout wrapper: this machine has no coreutils `timeout`.
# usage: ./tmo <seconds> <cmd> [args...]
S=$1; shift
exec nice -n 15 perl -e '
  my $s = shift @ARGV;
  my $pid = fork();
  die "fork: $!" unless defined $pid;
  if ($pid == 0) { exec @ARGV or die "exec: $!"; }
  $SIG{ALRM} = sub { kill "TERM", $pid; sleep 2; kill "KILL", $pid;
                     print STDERR "TIMEOUT after ${s}s\n"; exit 124; };
  alarm $s;
  waitpid($pid, 0);
  alarm 0;
  exit($? >> 8);
' "$S" "$@"
