#!/bin/sh
# ffto SECONDS COMMAND... -- nice(15) + hard timeout. This machine has no
# coreutils `timeout`, so the alarm is a perl wrapper that SIGKILLs the whole
# process group of the child (C test binaries can hang).
S="$1"; shift
exec nice -n 15 perl -e '
  my $s = shift @ARGV;
  my $pid = fork();
  die "fork: $!" unless defined $pid;
  if ($pid == 0) { setpgrp(0,0); exec @ARGV or die "exec: $!"; }
  $SIG{ALRM} = sub { kill(-9,$pid); waitpid($pid,0);
                     print STDERR "\n[ffto] TIMEOUT after ${s}s\n"; exit 124; };
  alarm $s;
  waitpid($pid, 0);
  alarm 0;
  exit($? >> 8);
' "$S" "$@"
