"""Sixteen functions whose specifications turn on a boundary — where models actually slip.

Nothing here is chosen because fluidfix can repair it. They are chosen because the prose fixes a convention
that is easy to get one step wrong: a ceiling rather than a floor, an exclusive bound rather than an
inclusive one, a half-open interval, a count of windows, a nearest rank. The writer sees the prose only.
"""

SPECS = [
    ("page_count",
     'def page_count(total_items, per_page):\n    """Number of pages needed to show all items, with a partial final page counted.\n    Zero items means zero pages."""',
     ["assert page_count(10, 5) == 2", "assert page_count(11, 5) == 3", "assert page_count(0, 5) == 0",
      "assert page_count(1, 5) == 1"]),
    ("windows",
     'def windows(items, size):\n    """Every consecutive run of exactly `size` elements, in order.\n    Fewer items than `size` gives an empty list."""',
     ["assert windows([1,2,3,4], 2) == [[1,2],[2,3],[3,4]]", "assert windows([1,2], 3) == []",
      "assert windows([1,2,3], 3) == [[1,2,3]]"]),
    ("between",
     'def between(value, low, high):\n    """True when value lies strictly between low and high, touching neither end."""',
     ["assert between(5, 1, 10) is True", "assert between(1, 1, 10) is False",
      "assert between(10, 1, 10) is False", "assert between(0, 1, 10) is False"]),
    ("nth_from_end",
     'def nth_from_end(items, n):\n    """The nth element counting back from the end, where n=1 is the last element."""',
     ["assert nth_from_end([1,2,3], 1) == 3", "assert nth_from_end([1,2,3], 3) == 1"]),
    ("split_at",
     'def split_at(items, index):\n    """Split into (before, after) where `before` holds the first `index` elements."""',
     ["assert split_at([1,2,3,4], 2) == ([1,2],[3,4])", "assert split_at([1,2], 0) == ([],[1,2])",
      "assert split_at([1,2], 2) == ([1,2],[])"]),
    ("overlap",
     'def overlap(a_start, a_end, b_start, b_end):\n    """True when two half-open intervals [start, end) share at least one point."""',
     ["assert overlap(0, 5, 3, 8) is True", "assert overlap(0, 5, 5, 8) is False",
      "assert overlap(0, 5, 4, 8) is True", "assert overlap(5, 8, 0, 5) is False"]),
    ("truncate_words",
     'def truncate_words(text, limit):\n    """Keep at most `limit` words. If any were dropped, add a single trailing ellipsis\n    as a separate word."""',
     ["assert truncate_words('a b c d', 2) == 'a b ...'", "assert truncate_words('a b', 5) == 'a b'",
      "assert truncate_words('a b c', 3) == 'a b c'"]),
    ("bytes_human",
     'def bytes_human(n):\n    """Format a byte count with one decimal using 1024 steps: 1024 -> \'1.0 KB\',\n    1023 -> \'1023.0 B\', 1048576 -> \'1.0 MB\'."""',
     ["assert bytes_human(1024) == '1.0 KB'", "assert bytes_human(1023) == '1023.0 B'",
      "assert bytes_human(1048576) == '1.0 MB'"]),
    ("insert_sorted",
     'def insert_sorted(items, value):\n    """Insert into a sorted list, placing the value AFTER any equal values."""',
     ["assert insert_sorted([1,2,2,3], 2) == [1,2,2,2,3]", "assert insert_sorted([], 1) == [1]",
      "assert insert_sorted([1,3], 2) == [1,2,3]"]),
    ("backoff",
     'def backoff(attempts, base):\n    """The delay before each retry, doubling each time and starting at `base`.\n    One entry per attempt."""',
     ["assert backoff(3, 1) == [1,2,4]", "assert backoff(1, 2) == [2]", "assert backoff(0, 1) == []"]),
    ("percentile",
     'def percentile(values, p):\n    """Nearest-rank percentile of a non-empty list: the value at rank ceil(p/100 * n),\n    counting from 1 in the sorted order."""',
     ["assert percentile([1,2,3,4], 50) == 2", "assert percentile([1,2,3,4], 100) == 4",
      "assert percentile([1,2,3,4], 25) == 1"]),
    ("clip_exclusive",
     'def clip_exclusive(index, length):\n    """Clip an index into the valid positions of a sequence of `length` items."""',
     ["assert clip_exclusive(7, 5) == 4", "assert clip_exclusive(-3, 5) == 0", "assert clip_exclusive(2, 5) == 2"]),
    ("columns",
     'def columns(items, n):\n    """Deal items across `n` columns row by row, returning one list per column.\n    Earlier columns take the extra items when it does not divide evenly."""',
     ["assert columns([1,2,3,4,5], 2) == [[1,3,5],[2,4]]", "assert columns([1,2], 3) == [[1],[2],[]]"]),
    ("countdown",
     'def countdown(start):\n    """Every whole number from `start` down to 1, in order. Zero or less gives nothing."""',
     ["assert countdown(3) == [3,2,1]", "assert countdown(1) == [1]", "assert countdown(0) == []"]),
    ("trim_to_fit",
     'def trim_to_fit(words, width):\n    """Take words from the front while the joined line stays within `width` characters,\n    counting the single spaces between them."""',
     ["assert trim_to_fit(['ab','cd'], 5) == ['ab','cd']", "assert trim_to_fit(['ab','cd'], 4) == ['ab']",
      "assert trim_to_fit(['abc'], 2) == []"]),
    ("progress",
     'def progress(done, total, width):\n    """How many cells of a bar `width` wide should be filled, rounded down.\n    A finished job fills every cell; zero total fills none."""',
     ["assert progress(1, 2, 10) == 5", "assert progress(2, 2, 10) == 10", "assert progress(0, 0, 10) == 0",
      "assert progress(1, 3, 10) == 3"]),
]
