"""Sixteen ordinary utility functions, specified in prose, with tests the writer never sees.

The point of this set is that it was NOT chosen to suit fluidfix's vocabulary. These are the sort of small
functions anyone writes: boundaries, indices, accumulations, string handling, a little parsing. Whatever
bugs a model makes here, it makes on its own.

Each entry: (name, signature + docstring shown to the writer, hidden tests).
"""

SPECS = [
    ("clamp",
     'def clamp(value, low, high):\n    """Return value limited to the inclusive range [low, high]."""',
     ["assert clamp(5, 1, 10) == 5", "assert clamp(0, 1, 10) == 1", "assert clamp(11, 1, 10) == 10",
      "assert clamp(1, 1, 10) == 1", "assert clamp(10, 1, 10) == 10"]),
    ("last_index",
     'def last_index(items):\n    """Return the index of the final element, or -1 for an empty list."""',
     ["assert last_index([1, 2, 3]) == 2", "assert last_index([]) == -1", "assert last_index([9]) == 0"]),
    ("chunk",
     'def chunk(items, size):\n    """Split items into consecutive lists of at most `size` elements."""',
     ["assert chunk([1,2,3,4,5], 2) == [[1,2],[3,4],[5]]", "assert chunk([], 3) == []",
      "assert chunk([1,2,3], 3) == [[1,2,3]]"]),
    ("running_total",
     'def running_total(numbers):\n    """Return the cumulative sums: [1,2,3] -> [1,3,6]."""',
     ["assert running_total([1,2,3]) == [1,3,6]", "assert running_total([]) == []",
      "assert running_total([5]) == [5]"]),
    ("median",
     'def median(numbers):\n    """Return the median of a non-empty list of numbers (mean of the middle two when even)."""',
     ["assert median([3,1,2]) == 2", "assert median([4,1,2,3]) == 2.5", "assert median([7]) == 7"]),
    ("truncate",
     'def truncate(text, limit):\n    """Return text unchanged when it fits in `limit` characters, otherwise cut it\n    and end with an ellipsis so the result is exactly `limit` characters long."""',
     ["assert truncate('hello', 10) == 'hello'", "assert truncate('hello', 5) == 'hello'",
      "assert truncate('hello world', 8) == 'hello...'", "assert len(truncate('abcdefgh', 6)) == 6"]),
    ("count_words",
     'def count_words(text):\n    """Return the number of whitespace-separated words; an empty or blank string has none."""',
     ["assert count_words('a b  c') == 3", "assert count_words('') == 0", "assert count_words('   ') == 0"]),
    ("is_leap",
     'def is_leap(year):\n    """True when the year is a leap year in the Gregorian calendar."""',
     ["assert is_leap(2024) is True", "assert is_leap(1900) is False", "assert is_leap(2000) is True",
      "assert is_leap(2023) is False"]),
    ("percent",
     'def percent(part, whole):\n    """Return part as a percentage of whole, rounded to one decimal; 0.0 when whole is 0."""',
     ["assert percent(1, 4) == 25.0", "assert percent(0, 0) == 0.0", "assert percent(1, 3) == 33.3"]),
    ("dedupe",
     'def dedupe(items):\n    """Remove duplicates, keeping the first occurrence and the original order."""',
     ["assert dedupe([1,2,1,3,2]) == [1,2,3]", "assert dedupe([]) == []", "assert dedupe([2,2]) == [2]"]),
    ("pairs",
     'def pairs(items):\n    """Return each element paired with the one after it: [1,2,3] -> [(1,2),(2,3)]."""',
     ["assert pairs([1,2,3]) == [(1,2),(2,3)]", "assert pairs([1]) == []", "assert pairs([]) == []"]),
    ("initials",
     'def initials(full_name):\n    """Return the uppercase initials of each word: \'ada lovelace\' -> \'AL\'."""',
     ["assert initials('ada lovelace') == 'AL'", "assert initials('grace') == 'G'", "assert initials('') == ''"]),
    ("clip_index",
     'def clip_index(index, length):\n    """Return a valid index into a sequence of `length` items, clipped into range;\n    a negative index counts from the end as Python does."""',
     ["assert clip_index(2, 5) == 2", "assert clip_index(9, 5) == 4", "assert clip_index(-1, 5) == 4",
      "assert clip_index(-9, 5) == 0"]),
    ("parse_duration",
     'def parse_duration(text):\n    """Parse \'1h30m\' or \'45s\' into whole seconds. Missing units are zero."""',
     ["assert parse_duration('45s') == 45", "assert parse_duration('1h30m') == 5400",
      "assert parse_duration('2m') == 120"]),
    ("balanced",
     'def balanced(text):\n    """True when every round bracket in the text is opened before it is closed and all are closed."""',
     ["assert balanced('(a(b))') is True", "assert balanced('(') is False", "assert balanced(')(') is False",
      "assert balanced('') is True"]),
    ("average_or_zero",
     'def average_or_zero(numbers):\n    """Return the mean, or 0 when the list is empty."""',
     ["assert average_or_zero([2,4]) == 3", "assert average_or_zero([]) == 0", "assert average_or_zero([5]) == 5"]),
]
