"""The observation byte the law was handed on run A1, and the byte the
situation actually was.  python byte_evidence.py"""
import sys
sys.path.insert(0, "/Users/kanchetidevieswar/neo/fluidfix/src")
from fluidfix.engine import decide, situation, BITS, ACTS

def show(label, **kw):
    s = situation(**kw)
    on = [b for b in BITS if kw.get(b)] or ["(none)"]
    print(f"{label}\n  byte = 0x{s:04x} ({s})   bits set: {'+'.join(on)}"
          f"   law's act: {decide(s)}")

show("AS MEASURED by loop._rule at run A1 (1 green, 1 site, not capped):",
     BUILT=True, AMB=False, CAPPED=False)
show("AS IT ACTUALLY WAS -- a second green program exists at "
     "ledger/billing.py:6\n(`over = used - included`, generated byte-exact by "
     "kind 1 / act 6):", BUILT=True, AMB=True, CAPPED=False)
print("\nBITS =", BITS, "\nACTS =", ACTS)
