#!/bin/sh
# timeout wrapper: this machine has no coreutils `timeout`.
# usage: ./runlim SECONDS cmd args...
S="$1"; shift
exec nice -n 15 perl -e '
  my $s = shift @ARGV;
  my $pid = fork();
  if ($pid == 0) { exec @ARGV or exit 127; }
  $SIG{ALRM} = sub { kill "TERM", $pid; sleep 2; kill "KILL", $pid; waitpid($pid,0); exit 124; };
  alarm $s;
  waitpid($pid, 0);
  my $rc = $? >> 8;
  alarm 0;
  exit $rc;
' "$S" "$@"
