#!/bin/sh
# timeout wrapper: this machine has no coreutils `timeout`.
#   usage: ./tmo SECONDS cmd args...
# runs the command niced, kills the whole process group on expiry.
SECS="$1"; shift
exec nice -n 15 perl -e '
  my $t = shift @ARGV;
  my $pid = fork();
  if ($pid == 0) { setpgrp(0,0); exec @ARGV; exit 127; }
  $SIG{ALRM} = sub { kill(-9, $pid); waitpid($pid, 0); print STDERR "\n[tmo] TIMEOUT after $t s\n"; exit 124; };
  alarm $t;
  waitpid($pid, 0);
  my $rc = $? >> 8;
  alarm 0;
  exit $rc;
' "$SECS" "$@"
