"""One regression per shipped class, three taught classes, the cap knob, an
ambiguity, a novel class, and a green run. `expect` is declared BEFORE the run:
repair = the pristine bytes must come back; refuse = exit 2, tree untouched;
green = nothing to do. A wrong repair is a green suite that is not pristine."""
CASES = [
 dict(id="R01", kind="0 strictness", file="ledgerkit/discounts.py",
      old="    if qty >= BULK_MIN:", new="    if qty > BULK_MIN:", expect="repair"),
 dict(id="R02", kind="1 literal-off-by-one", file="ledgerkit/text.py",
      old="    return fields[1:]", new="    return fields[2:]", expect="repair"),
 dict(id="R03", kind="2 swapped-return-operands", file="ledgerkit/tax.py",
      old="    return total / units", new="    return units / total", expect="repair"),
 dict(id="R04", kind="3 flipped-additive", file="ledgerkit/tax.py",
      old="    return net * (1 + rate)", new="    return net * (1 - rate)", expect="repair"),
 dict(id="R05", kind="8 minmax-swap", file="ledgerkit/money.py",
      old="    return max(0.0, amount)", new="    return min(0.0, amount)", expect="repair"),
 dict(id="R06", kind="9 flipped-augmented-assign", file="ledgerkit/inventory.py",
      old="            it.qty += amount", new="            it.qty -= amount", expect="repair"),
 dict(id="R07", kind="10 flipped-comparison-direction", file="ledgerkit/discounts.py",
      old="    if amount < 100:", new="    if amount > 100:", expect="repair"),
 dict(id="R08", kind="11 reversed-minus-operands", file="ledgerkit/schedule.py",
      old="    return end - start", new="    return start - end", expect="repair"),
 dict(id="R09", kind="12 flipped-boolean", file="ledgerkit/inventory.py",
      old='    return item.get("taxable", True)', new='    return item.get("taxable", False)', expect="repair"),
 dict(id="R10", kind="4 taught: round-lost-precision", file="ledgerkit/money.py",
      old="    return round(amount, 2)", new="    return round(amount)", expect="repair"),
 dict(id="R11", kind="5 taught: wrong-attribute (repo-mined set)", file="ledgerkit/inventory.py",
      old="    return item.sku", new="    return item.name", expect="repair"),
 dict(id="R12", kind="6 taught: two lines together (SpanEdit)", file="ledgerkit/money.py",
      old="    total = subtotal + surcharge\n    total = round(total)",
      new="    total = round(subtotal)\n    total = total + surcharge", expect="repair"),
 dict(id="R13", kind="6 taught, FLUIDFIX_MAX_LINES=1 (the cap)", file="ledgerkit/money.py",
      old="    total = subtotal + surcharge\n    total = round(total)",
      new="    total = round(subtotal)\n    total = total + surcharge", expect="refuse",
      env={"FLUIDFIX_MAX_LINES": "1"}),
 dict(id="R14", kind="ambiguity: two different programs both green", file="ledgerkit/text.py",
      old="    return n * 2 - 1", new="    return n * 2 + 1", expect="refuse"),
 dict(id="R15", kind="novel class, untaught", file="ledgerkit/text.py",
      old='    parts = line.split(",")', new="    parts = line.split()", expect="refuse"),
 dict(id="R16", kind="green suite", file=None, old=None, new=None, expect="green"),
]
